In [2]:
import glob

In [41]:
lecs = glob.glob(r"C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\*")

In [29]:
len(lecs)

27

In [42]:
lecs

['C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C1M1.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C1M2.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C1M3.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C1M4.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C2M1.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C2M2.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C2M3.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C3M1.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C3M2.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C4M1.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C4M2.pdf',
 'C:\\Users\\feroc\\OneDrive\\Notability\\CS230 Deep Learning\\coursera\\C4M

In [7]:
import re

In [21]:
empty_dict = dict([])
for i in lecs:
    empty_dict[int(re.search('(?<=[a-z]{3})([0-9]{1,2})', i)[0])] = i

In [25]:
sorted(empty_dict)

list

In [26]:
[empty_dict[i] for i in sorted(empty_dict)]

['lec1_scribe.pdf',
 'lec2_scribe.pdf',
 'lec3_scribe.pdf',
 'lec4_scribe.pdf',
 'lec5_scribe.pdf',
 'lec7_scribe.pdf',
 'lec8_scribe.pdf',
 'lec9_scribe.pdf',
 'lec10_scribe.pdf',
 'lec11_scribe.pdf',
 'lec12_scribe.pdf',
 'lec13_scribe.pdf',
 'lec14_scribe.pdf',
 'lec15_scribe.pdf',
 'lec16_scribe.pdf',
 'lec17_scribe.pdf',
 'lec18_scribe.pdf',
 'lec19_scribe.pdf',
 'lec20_scribe.pdf',
 'lec21_scribe.pdf',
 'lec23_scribe.pdf',
 'lec24_scribe.pdf']

In [43]:
from PyPDF3 import PdfFileMerger

pdfs = lecs

merger = PdfFileMerger()

for pdf in pdfs:
    merger.append(pdf)
    print(f"{pdf} successful")

merger.write("coursera_DL_all.pdf")
merger.close()

C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C1M1.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C1M2.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C1M3.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C1M4.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C2M1.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C2M2.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C2M3.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C3M1.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C3M2.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C4M1.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C4M2.pdf successful
C:\Users\feroc\OneDrive\Notability\CS230 Deep Learning\coursera\C4M3.pdf suc

In [44]:
import numpy as np

In [48]:
a= np.random.random((5,5))

In [49]:
a

array([[0.26309842, 0.39597966, 0.67174677, 0.51293235, 0.12907635],
       [0.01597168, 0.32393006, 0.64516106, 0.38632185, 0.66908406],
       [0.90915352, 0.56832328, 0.77685333, 0.05104508, 0.41929947],
       [0.57909994, 0.58112241, 0.10782845, 0.46731235, 0.32701433],
       [0.58413619, 0.6975414 , 0.4398685 , 0.82988767, 0.37177517]])

In [52]:
b = np.random.random(5)

In [53]:
b

array([0.68502854, 0.78118431, 0.88364747, 0.7808659 , 0.49737972])

In [54]:
b.shape

(5,)

In [63]:
np.dot(b,a.T)

array([1.5478817 , 1.46853948, 2.00163624, 1.47350461, 2.16669145])

In [56]:
np.dot(b.T,a)

array([1.73881485, 1.8272255 , 1.95360112, 1.4759453 , 1.42187963])

In [59]:
np.array([0.26309842, 0.39597966, 0.67174677, 0.51293235, 0.12907635]).dot([0.68502854, 0.78118431, 0.88364747, 0.7808659 , 0.49737972])

1.5478816977347005